In [3]:
from configs import get_config
from solver import Solver
from data_loader import get_loader

In [10]:
import h5py

h5 = h5py.File('./data/datasets/TVSum/eccv16_dataset_tvsum_google_pool5.h5', 'r')
list_frame_features, list_gtscores = [], []
for k in h5.keys():
    print(h5[k].name)

/video_1
/video_10
/video_11
/video_12
/video_13
/video_14
/video_15
/video_16
/video_17
/video_18
/video_19
/video_2
/video_20
/video_21
/video_22
/video_23
/video_24
/video_25
/video_26
/video_27
/video_28
/video_29
/video_3
/video_30
/video_31
/video_32
/video_33
/video_34
/video_35
/video_36
/video_37
/video_38
/video_39
/video_4
/video_40
/video_41
/video_42
/video_43
/video_44
/video_45
/video_46
/video_47
/video_48
/video_49
/video_5
/video_50
/video_6
/video_7
/video_8
/video_9


In [11]:
for k, v in h5.items():
    print(k, v.name)

video_1 /video_1
video_10 /video_10
video_11 /video_11
video_12 /video_12
video_13 /video_13
video_14 /video_14
video_15 /video_15
video_16 /video_16
video_17 /video_17
video_18 /video_18
video_19 /video_19
video_2 /video_2
video_20 /video_20
video_21 /video_21
video_22 /video_22
video_23 /video_23
video_24 /video_24
video_25 /video_25
video_26 /video_26
video_27 /video_27
video_28 /video_28
video_29 /video_29
video_3 /video_3
video_30 /video_30
video_31 /video_31
video_32 /video_32
video_33 /video_33
video_34 /video_34
video_35 /video_35
video_36 /video_36
video_37 /video_37
video_38 /video_38
video_39 /video_39
video_4 /video_4
video_40 /video_40
video_41 /video_41
video_42 /video_42
video_43 /video_43
video_44 /video_44
video_45 /video_45
video_46 /video_46
video_47 /video_47
video_48 /video_48
video_49 /video_49
video_5 /video_5
video_50 /video_50
video_6 /video_6
video_7 /video_7
video_8 /video_8
video_9 /video_9


In [12]:
for v in h5.values():
    print(v.name)

/video_1
/video_10
/video_11
/video_12
/video_13
/video_14
/video_15
/video_16
/video_17
/video_18
/video_19
/video_2
/video_20
/video_21
/video_22
/video_23
/video_24
/video_25
/video_26
/video_27
/video_28
/video_29
/video_3
/video_30
/video_31
/video_32
/video_33
/video_34
/video_35
/video_36
/video_37
/video_38
/video_39
/video_4
/video_40
/video_41
/video_42
/video_43
/video_44
/video_45
/video_46
/video_47
/video_48
/video_49
/video_5
/video_50
/video_6
/video_7
/video_8
/video_9


In [16]:
import numpy as np
np.array(h5['/video_1/user_summary'])

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]], dtype=float32)

In [18]:
np.array(h5['/video_1/gtscore'])

array([0.475 , 0.475 , 0.475 , 0.475 , 0.175 , 0.175 , 0.175 , 0.175 ,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0875, 0.0875, 0.0875, 0.0875,
       0.075 , 0.075 , 0.075 , 0.075 , 0.05  , 0.05  , 0.05  , 0.05  ,
       0.1125, 0.1125, 0.1125, 0.1125, 0.0875, 0.0875, 0.0875, 0.0875,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0875, 0.0875, 0.0875, 0.0875,
       0.375 , 0.375 , 0.375 , 0.375 , 0.1125, 0.1125, 0.1125, 0.1125,
       0.15  , 0.15  , 0.15  , 0.15  , 0.2125, 0.2125, 0.2125, 0.2125,
       0.1875, 0.1875, 0.1875, 0.1875, 0.15  , 0.15  , 0.15  , 0.15  ,
       0.1625, 0.1625, 0.1625, 0.1625, 0.2125, 0.2125, 0.2125, 0.2125,
       0.175 , 0.175 , 0.175 , 0.175 , 0.1625, 0.1625, 0.1625, 0.1625,
       0.1125, 0.1125, 0.1125, 0.1125, 0.125 , 0.125 , 0.125 , 0.125 ,
       0.0375, 0.0375, 0.0375, 0.0375, 0.0875, 0.0875, 0.0875, 0.0875,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0375, 0.0375, 0.0375, 0.0375,
      

In [17]:
np.array(h5['/video_1/features'])

array([[0.03245889, 0.        , 0.00018815, ..., 0.02178879, 0.00443873,
        0.        ],
       [0.02346171, 0.        , 0.        , ..., 0.00393682, 0.002956  ,
        0.00285526],
       [0.01867428, 0.        , 0.        , ..., 0.01959703, 0.00158309,
        0.        ],
       ...,
       [0.01900744, 0.00319129, 0.00368785, ..., 0.0868216 , 0.        ,
        0.        ],
       [0.00916142, 0.00035935, 0.00784355, ..., 0.09495226, 0.        ,
        0.        ],
       [0.01148452, 0.0037852 , 0.00210227, ..., 0.09508222, 0.        ,
        0.        ]], dtype=float32)

In [20]:
np.array(h5['/video_1/n_frames'])

array(10597, dtype=int64)

In [21]:
np.array(h5['/video_1/n_steps'])

array(707, dtype=int64)

In [22]:
import json
with open("../data/datasets/splits/'tvsum'_splits.json") as f:
    data = json.loads(f.read())
    for i, split in enumerate(data):
        if i == 40:
            print(split)
            break

In [33]:
len(data)

5

In [1]:
import wget
url = 'https://zenodo.org/record/5635735/files/pretrained_models.zip?download=1'
wget.download(url)

'pretrained_models.zip'

In [ ]:
import cv