### Read H5

In [ ]:
/key
    /features                 2D-array with shape (n_steps, feature-dimension)
    /gtscore                  1D-array with shape (n_steps), stores ground truth importance score (used for training, e.g. regression loss)
    /user_summary             2D-array with shape (num_users, n_frames), each row is a binary vector (used for test)
    /change_points            2D-array with shape (num_segments, 2), each row stores indices of a segment
    /n_frame_per_seg          1D-array with shape (num_segments), indicates number of frames in each segment
    /n_frames                 number of frames in original video
    /picks                    positions of subsampled frames in original video
    /n_steps                  number of subsampled frames
    /gtsummary                1D-array with shape (n_steps), ground truth summary provided by user (used for training, e.g. maximum likelihood)
    /video_name (optional)    original video name, only available for SumMe dataset

In [1]:
import h5py

h5 = h5py.File('./data/datasets/TVSum/eccv16_dataset_tvsum_google_pool5.h5', 'r')
list_frame_features, list_gtscores = [], []
for k in h5.keys():
    print(h5[k].name)

/video_1
/video_10
/video_11
/video_12
/video_13
/video_14
/video_15
/video_16
/video_17
/video_18
/video_19
/video_2
/video_20
/video_21
/video_22
/video_23
/video_24
/video_25
/video_26
/video_27
/video_28
/video_29
/video_3
/video_30
/video_31
/video_32
/video_33
/video_34
/video_35
/video_36
/video_37
/video_38
/video_39
/video_4
/video_40
/video_41
/video_42
/video_43
/video_44
/video_45
/video_46
/video_47
/video_48
/video_49
/video_5
/video_50
/video_6
/video_7
/video_8
/video_9


In [2]:
for k, v in h5.items():
    print(k, v.name)

video_1 /video_1
video_10 /video_10
video_11 /video_11
video_12 /video_12
video_13 /video_13
video_14 /video_14
video_15 /video_15
video_16 /video_16
video_17 /video_17
video_18 /video_18
video_19 /video_19
video_2 /video_2
video_20 /video_20
video_21 /video_21
video_22 /video_22
video_23 /video_23
video_24 /video_24
video_25 /video_25
video_26 /video_26
video_27 /video_27
video_28 /video_28
video_29 /video_29
video_3 /video_3
video_30 /video_30
video_31 /video_31
video_32 /video_32
video_33 /video_33
video_34 /video_34
video_35 /video_35
video_36 /video_36
video_37 /video_37
video_38 /video_38
video_39 /video_39
video_4 /video_4
video_40 /video_40
video_41 /video_41
video_42 /video_42
video_43 /video_43
video_44 /video_44
video_45 /video_45
video_46 /video_46
video_47 /video_47
video_48 /video_48
video_49 /video_49
video_5 /video_5
video_50 /video_50
video_6 /video_6
video_7 /video_7
video_8 /video_8
video_9 /video_9


In [3]:
for v in h5.values():
    print(v.name)

/video_1
/video_10
/video_11
/video_12
/video_13
/video_14
/video_15
/video_16
/video_17
/video_18
/video_19
/video_2
/video_20
/video_21
/video_22
/video_23
/video_24
/video_25
/video_26
/video_27
/video_28
/video_29
/video_3
/video_30
/video_31
/video_32
/video_33
/video_34
/video_35
/video_36
/video_37
/video_38
/video_39
/video_4
/video_40
/video_41
/video_42
/video_43
/video_44
/video_45
/video_46
/video_47
/video_48
/video_49
/video_5
/video_50
/video_6
/video_7
/video_8
/video_9


In [4]:
import numpy as np
np.array(h5['/video_1/user_summary'])

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]], dtype=float32)

In [5]:
np.array(h5['/video_1/gtscore'])

array([0.475 , 0.475 , 0.475 , 0.475 , 0.175 , 0.175 , 0.175 , 0.175 ,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0875, 0.0875, 0.0875, 0.0875,
       0.075 , 0.075 , 0.075 , 0.075 , 0.05  , 0.05  , 0.05  , 0.05  ,
       0.1125, 0.1125, 0.1125, 0.1125, 0.0875, 0.0875, 0.0875, 0.0875,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0875, 0.0875, 0.0875, 0.0875,
       0.375 , 0.375 , 0.375 , 0.375 , 0.1125, 0.1125, 0.1125, 0.1125,
       0.15  , 0.15  , 0.15  , 0.15  , 0.2125, 0.2125, 0.2125, 0.2125,
       0.1875, 0.1875, 0.1875, 0.1875, 0.15  , 0.15  , 0.15  , 0.15  ,
       0.1625, 0.1625, 0.1625, 0.1625, 0.2125, 0.2125, 0.2125, 0.2125,
       0.175 , 0.175 , 0.175 , 0.175 , 0.1625, 0.1625, 0.1625, 0.1625,
       0.1125, 0.1125, 0.1125, 0.1125, 0.125 , 0.125 , 0.125 , 0.125 ,
       0.0375, 0.0375, 0.0375, 0.0375, 0.0875, 0.0875, 0.0875, 0.0875,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.0625, 0.0625, 0.0625, 0.0375, 0.0375, 0.0375, 0.0375,
      

In [6]:
np.array(h5['/video_1/features'])

array([[0.03245889, 0.        , 0.00018815, ..., 0.02178879, 0.00443873,
        0.        ],
       [0.02346171, 0.        , 0.        , ..., 0.00393682, 0.002956  ,
        0.00285526],
       [0.01867428, 0.        , 0.        , ..., 0.01959703, 0.00158309,
        0.        ],
       ...,
       [0.01900744, 0.00319129, 0.00368785, ..., 0.0868216 , 0.        ,
        0.        ],
       [0.00916142, 0.00035935, 0.00784355, ..., 0.09495226, 0.        ,
        0.        ],
       [0.01148452, 0.0037852 , 0.00210227, ..., 0.09508222, 0.        ,
        0.        ]], dtype=float32)

In [117]:
np.array(h5['/video_1/features']).shape

(707, 1024)

In [7]:
np.array(h5['/video_1/n_frames'])

array(10597, dtype=int64)

In [8]:
np.array(h5['/video_1/n_steps'])

array(707, dtype=int64)

### Read TvSum

In [11]:
f = open ('./data/ydata-tvsum50-v1_1/ydata-tvsum50-data/data/ydata-tvsum50-info.tsv', 'r')
data = f.readlines()
f.close()

In [28]:
cate = []
id = []
title = []
url = []
length = []
n = [] 
for d in data[1:]:
    temps = d.split("\t")
    cate.append(temps[0])
    id.append(temps[1])
    title.append(temps[2])
    url.append(temps[3])
    length.append(temps[4])
    try:
        n.append(temps[5])
    except:
        n.append(np.nan)        

In [34]:
df = pd.DataFrame([cate, id, title, url, length]).T
df.columns = ['category', 'id', 'title', 'url', 'length']
df

category           id                                              title  \
0        VT  AwmHb44_ouw  #1306 How to change tires for off road vehicle...   
1        VT  98MoyGZKHXc        How to use a tyre repair kit - Which? guide   
2        VT  J0nA4VgnoCo                                   #0001: FLAT TIRE   
3        VT  gzDbaEs1Rlg                 ŠKODA Tips How to Repair Your Tyre   
4        VT  XzYM3PfTM4w                     When to Replace Your Tires GMC   
5        VU  HT5vyqe0Xaw  "The stuck truck of Mark, The rut that filled ...   
6        VU  sTEELN-vY30                             BBC - Train crash 2013   
7        VU  vdmoEJ5YbrQ  #453 girl gets van stuck in the back fourty [D...   
8        VU  xwqBXPGE9pQ      Smart Electric Vehicle Balances on Two Wheels   
9        VU  akI8YFjEmUw              Electric cars making earth more green   
10       GA  i3wAGJaaktw  "Pet Joy Spa Grooming Services | Brentwood, CA...   
11       GA  Bhxk-O1Y7Ho  "Vlog #509 I'M A PUPPY DOG GROOMER! September ...   
12       GA  0tmA_C6XwfM     Nail clipper Gloria Pets professional grooming   
13       GA  3eYKfiOEJNs                       Dog Grooming in Buenos Aires   
14       GA  xxdtq8mxegs      How to Clean Your Dog's Ears - Vetoquinol USA   
15       MS  WG0MBPpPC6I              Mexican Fried Chicken Sandwich Recipe   
16       MS  Hl-__g2gn_A      Reuben Sandwich with Corned Beef & Sauerkraut   
17       MS  Yi4Ij2NM7U4           Poor Man's Meals: Spicy Sausage Sandwich   
18       MS  37rzWOQsNIw  Saigon Sandwich - Vietnamese Sandwiches in San...   
19       MS  LRw_obCPUt0  GoogaMooga Sneak Peek Joseph Leonard's Fried C...   
20       PK  cjibtmSLxQ4  David Belle | Fondateur du parkour | Reportage...   
21       PK  b626MiF1ew4        Charlotte Parkour | Charlotte Video Project   
22       PK  XkqCExn6_Us  Singapore Parkour Free Running | JC Boy Late f...   
23       PK  GsAD1KT1xo8                               Parkour Camp Leipzig   
24       PK  PJrm840pAUI           Vivencias: Jam Parkour Viña del Mar 2012   
25       PR  91IHQYk1IQM  Chinese New Year Parade 2012 New York City Chi...   
26       PR  RBCABdttQmI        2013 Alumnae Parade & Laurel Chain Ceremony   
27       PR  z_6gVvQb2d0         LA Kings Stanley Cup South Bay Parade 2014   
28       PR  fWutDQy1nnY                                   Chinatown Parade   
29       PR  4wU_LUjG5Ic  Southend-on-Sea and Kortrijk Bike Friendly Cit...   
30       FM  VuWGsYPqAX8  "Flash mob protest for Syria | Sydney, Austral...   
31       FM  JKpqYvAdIsw  ICC World Twenty20 Bangladesh 2014 Flash Mob -...   
32       FM  xmEERLqJ2kU  Bluffton Teachers Flash Mob Dance (A Staff tha...   
33       FM  byxOvuiIJV0  "ICC World Twenty 20 Bangladesh 2014, Flash Mo...   
34       FM  _xMr-HKMfVA  CASACL - Flashmob in Copenhagen underground - ...   
35       BK  WxtbjNsCQ8A                                  Beekeeping101.mov   
36       BK  uGu_10sucQo                               A Year of Beekeeping   
37       BK  EE-bNr36nyA            Paper Wasp Removal | From the Ground Up   
38       BK  Se3oxnaPsz0  9/15/11 Killer Bees Kill 1000-lb Hog in Bisbee AZ   
39       BK  oDXZc0tZe04              Apis Mellifera in a Vertical Log Hive   
40       BT  qqR6AEXwxoQ  Motocross Tips & Tricks : How to Whip a Motocr...   
41       BT  EYqVtI9YWJA                  Smage Bros. Motorcycle Stunt Show   
42       BT  eQu1rNs0an0                             How to stop your Fixie   
43       BT  JgHubY5Vw3Y              How to lock your bike. The RIGHT way!   
44       BT  iVt07TCkFM0                        Pure Fix TV: How to Wheelie   
45       DS  E11zDS9XGzg         German Shepherd Dog Show (KCI) | DoHangout   
46       DS  NyBmCxDoHJU                               The Dog Show HD 720p   
47       DS  kLxoNp-UchI                         Oliver's Show - Dog's tale   
48       DS  jcoYJXDG9sw  TODAY- Obie the obese dog works toward weight ...   
49       DS  -esJrBWj2d8                           Wi

In [35]:
f = open ('./data/ydata-tvsum50-v1_1/ydata-tvsum50-data/data/ydata-tvsum50-anno.tsv', 'r')
data = f.readlines()
f.close()

In [46]:
info = []
anno = []
for d in data:
    temps = d.split(',')
    info.append(temps[0])
    anno.append(temps[1:])

In [49]:
info[1]

'AwmHb44_ouw\tVT\t2'

In [51]:
anno[1]

['2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1'

In [50]:
len(anno[1])

10596

In [52]:
len(info)

1000

In [53]:
import cv2
cap = cv2.VideoCapture('data/ydata-tvsum50-v1_1/ydata-tvsum50-video/video/AwmHb44_ouw.mp4')
cap

<VideoCapture 000002178E66A6D0>

In [54]:
width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
fps = cap.get(cv2.CAP_PROP_FPS)

print('가로: ', str(width) )
print('세로: ', str(height) )
print('총 프레임수: ', str(count) )
print('FPS: ', str(fps) )

가로:  540.0
세로:  360.0
총 프레임수:  10597.0
FPS:  29.97002997002997


#### inference용 h5 subset

In [60]:
# positions of subsampled frames in original video
np.array(h5['/video_1/picks'])

array([    0,    15,    30,    45,    60,    75,    90,   105,   120,
         135,   150,   165,   180,   195,   210,   225,   240,   255,
         270,   285,   300,   315,   330,   345,   360,   375,   390,
         405,   420,   435,   450,   465,   480,   495,   510,   525,
         540,   555,   570,   585,   600,   615,   630,   645,   660,
         675,   690,   705,   720,   735,   750,   765,   780,   795,
         810,   825,   840,   855,   870,   885,   900,   915,   930,
         945,   960,   975,   990,  1005,  1020,  1035,  1050,  1065,
        1080,  1095,  1110,  1125,  1140,  1155,  1170,  1185,  1200,
        1215,  1230,  1245,  1260,  1275,  1290,  1305,  1320,  1335,
        1350,  1365,  1380,  1395,  1410,  1425,  1440,  1455,  1470,
        1485,  1500,  1515,  1530,  1545,  1560,  1575,  1590,  1605,
        1620,  1635,  1650,  1665,  1680,  1695,  1710,  1725,  1740,
        1755,  1770,  1785,  1800,  1815,  1830,  1845,  1860,  1875,
        1890,  1905,

In [62]:
np.array(h5['/video_1/features'])

array([[0.03245889, 0.        , 0.00018815, ..., 0.02178879, 0.00443873,
        0.        ],
       [0.02346171, 0.        , 0.        , ..., 0.00393682, 0.002956  ,
        0.00285526],
       [0.01867428, 0.        , 0.        , ..., 0.01959703, 0.00158309,
        0.        ],
       ...,
       [0.01900744, 0.00319129, 0.00368785, ..., 0.0868216 , 0.        ,
        0.        ],
       [0.00916142, 0.00035935, 0.00784355, ..., 0.09495226, 0.        ,
        0.        ],
       [0.01148452, 0.0037852 , 0.00210227, ..., 0.09508222, 0.        ,
        0.        ]], dtype=float32)

In [69]:
np.array(h5['/video_1/features']).shape

(707, 1024)

In [64]:
np.array(h5['/video_1/user_summary'])

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]], dtype=float32)

In [68]:
np.array(h5['/video_1/user_summary']).shape

(20, 10597)

In [65]:
np.array(h5['/video_1/change_points'])

array([[    0,    32],
       [   33,    63],
       [   64,   101],
       [  102,   295],
       [  296,   592],
       [  593,   685],
       [  686,  1229],
       [ 1230,  1692],
       [ 1693,  1727],
       [ 1728,  1758],
       [ 1759,  1786],
       [ 1787,  1857],
       [ 1858,  1982],
       [ 1983,  2214],
       [ 2215,  2349],
       [ 2350,  2461],
       [ 2462,  2522],
       [ 2523,  2690],
       [ 2691,  2841],
       [ 2842,  3025],
       [ 3026,  3155],
       [ 3156,  3258],
       [ 3259,  3331],
       [ 3332,  3426],
       [ 3427,  3466],
       [ 3467,  3523],
       [ 3524,  3599],
       [ 3600,  3923],
       [ 3924,  4017],
       [ 4018,  4143],
       [ 4144,  4213],
       [ 4214,  4266],
       [ 4267,  4414],
       [ 4415,  4539],
       [ 4540,  4625],
       [ 4626,  4646],
       [ 4647,  4773],
       [ 4774,  4950],
       [ 4951,  5035],
       [ 5036,  5169],
       [ 5170,  5234],
       [ 5235,  5362],
       [ 5363,  5604],
       [ 56

In [67]:
np.array(h5['/video_1/change_points']).shape

(71, 2)

In [66]:
np.array(h5['/video_1/n_frames'])

array(10597, dtype=int64)

#### YouTube Sample

In [72]:
cap = cv2.VideoCapture('https://www.youtube.com/watch?v=EV-5_ZBq5y4')

In [73]:
width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
fps = cap.get(cv2.CAP_PROP_FPS)

print('가로: ', str(width) )
print('세로: ', str(height) )
print('총 프레임수: ', str(count) )
print('FPS: ', str(fps) )

가로:  0.0
세로:  0.0
총 프레임수:  0.0
FPS:  0.0


In [74]:
# URL로 동영상 불러오기 실패

#### AI Hub Sample

In [82]:
import json

with open('./data/AIhub/Training/video_summary_training_data.json', 'r') as f:
    json_data = json.load(f)
json_data[0].keys()

dict_keys(['filename', 'category', 'length', 'quality', 'license', 'ad_start', 'ad_end', 'three_secs', 'path', 'annots'])

In [91]:
len(json_data)

1606

In [102]:
import os
trr_lst = os.listdir('./data/AIhub/Training/SUMVID_MEDIUM_TRAIN_01/')
tr_lst = []
for lst in trr_lst:
    tr_lst.append(lst[:-4])

In [104]:
train_idx = []
for idx, data in enumerate(json_data):
    if data['filename'] in (tr_lst):
        train_idx.append(idx)

In [105]:
train_idx

[26,
 34,
 42,
 99,
 106,
 134,
 166,
 175,
 182,
 191,
 199,
 200,
 203,
 209,
 219,
 221,
 222,
 224,
 229,
 241,
 298,
 306,
 327,
 335,
 344,
 355,
 359,
 376,
 400,
 403,
 429,
 475,
 502,
 503,
 511,
 513,
 518,
 539,
 572,
 573,
 582,
 619,
 634,
 653,
 661,
 669,
 714,
 722,
 780,
 788,
 794,
 824,
 828,
 829,
 835,
 840,
 847,
 849,
 855,
 863,
 893,
 902,
 904,
 909,
 923,
 933,
 941,
 966,
 997,
 1035,
 1036,
 1039,
 1050,
 1068,
 1071,
 1082,
 1106,
 1112,
 1119,
 1126,
 1127,
 1129,
 1137,
 1146,
 1166,
 1208,
 1215,
 1219,
 1227,
 1254,
 1257,
 1258,
 1272,
 1285,
 1290,
 1292,
 1307,
 1308,
 1323,
 1328,
 1340,
 1376,
 1384,
 1396,
 1409,
 1442,
 1443,
 1481,
 1491,
 1506,
 1518,
 1522,
 1562,
 1563]

In [107]:
len(train_idx)

114

In [109]:
json_data[train_idx[2]]

{'filename': '0be7a3bcb2cf2b779387d24aac721e9c83b62a993e851b51ba46fb38c5f16507-유튜브 영상물(5~20분) 장면별 중요도 태그-100177-20201217181222-001-001',
 'category': '여행',
 'length': 573.467,
 'quality': '720p',
 'license': 'Youtube',
 'ad_start': '-',
 'ad_end': '-',
 'three_secs': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  1

In [145]:
# 'three_secs', 'path', 'annots'
json_data[42]['three_secs']

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [84]:
with open('./data/AIhub/Validation/video_summary_validation_data.json', 'r') as f:
    json_data_2 = json.load(f)
json_data_2[0].keys()

dict_keys(['filename', 'category', 'length', 'quality', 'license', 'ad_start', 'ad_end', 'three_secs', 'path', 'annots'])

In [86]:
json_data_2[0]['filename']

'f93e401a0d6bd398ad9052de637b292572dd4cdf414cd0fdeb4e12135740bec1-유튜브 영상물(5~20분) 장면별 중요도 태그-100177-20201203190659-001-001'

### Make sample

In [120]:
# TvSum Dataset sample
import cv2
cap = cv2.VideoCapture('./data/ydata-tvsum50-v1_1/ydata-tvsum50-video/video/AwmHb44_ouw.mp4')

width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
fps = cap.get(cv2.CAP_PROP_FPS)

print('가로: ', str(width) )
print('세로: ', str(height) )
print('총 프레임수: ', str(count) )
print('FPS: ', str(fps) )

가로:  540.0
세로:  360.0
총 프레임수:  10597.0
FPS:  29.97002997002997


In [122]:
# AI hub Dataset sample
path = './data/AIhub/Training/SUMVID_MEDIUM_TRAIN_01/'
filename = json_data[42]['filename']
cap = cv2.VideoCapture(path + filename + '.mp4')

width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
fps = cap.get(cv2.CAP_PROP_FPS)

print('가로: ', str(width) )
print('세로: ', str(height) )
print('총 프레임수: ', str(count) )
print('FPS: ', str(fps) )

가로:  1280.0
세로:  720.0
총 프레임수:  13748.0
FPS:  23.976023976023978


In [148]:
# data['n_frames'] = count

In [147]:
# data['picks'] = range(0, int(count), 15)

In [151]:
temp = json_data[42]['annots'][0]['highlight']
print('pre:', temp)
temp = [(i+1) * 3 for i in temp]
print('after three:', temp)
temp = [i * int(fps) for i in temp]
print('final index:', temp)

pre: [14, 40, 52, 69, 84, 107, 134, 155, 172]
after three: [45, 123, 159, 210, 255, 324, 405, 468, 519]
final index: [1035, 2829, 3657, 4830, 5865, 7452, 9315, 10764, 11937]


In [158]:
# highlight = user summary의 index-fps ~ index 지점을 1로 변환 
user_summary = [0] * int(count)
len(user_summary)

13748

In [169]:
for idx in temp:
    i = idx-round(fps)
    for i in range(i, idx+1):
        user_summary[i] = 1

In [ ]:
# data['user_summary] = user_summary

In [172]:
# PySceneDetect
# 프레임 단위 전환점 자동 탐색
# !pip install scenedetect[opencv]
from scenedetect import VideoManager, SceneManager, StatsManager
from scenedetect.detectors import ContentDetector
from scenedetect.scene_manager import save_images, write_scene_list_html

In [191]:
video_path = './data/AIhub/Training/SUMVID_MEDIUM_TRAIN_01/0be7a3bcb2cf2b779387d24aac721e9c83b62a993e851b51ba46fb38c5f16507-유튜브 영상물(5~20분) 장면별 중요도 태그-100177-20201217181222-001-001.mp4'
stats_path = 'result.csv' # 영상의 각 프레임마다 전환점에 대한 점수를 나타냄

video_manager = VideoManager([video_path])
stats_manager = StatsManager()
scene_manager = SceneManager(stats_manager)

scene_manager.add_detector(ContentDetector(threshold=30)) # 0~100 까지, 낮을수록 민감하게 변화에 반응
                           # 가까운 프레임 간의 색상과 밝기 등을 비교해서 전환점을 탐색

video_manager.set_downscale_factor() # 처리 속도 향상을 위해 이미지 크기를 자동으로 줄임

video_manager.start()
scene_manager.detect_scenes(frame_source=video_manager)

# result
with open(stats_path, 'w') as f:
    stats_manager.save_to_csv(f, video_manager.get_base_timecode())

scene_list = scene_manager.get_scene_list()
print(f'{len(scene_list)} scenes detected!')

# 전환점 시작 장면으로 썸네일 추출
save_images(
    scene_list,
    video_manager,
    num_images=1,
    image_name_template='$SCENE_NUMBER',
    output_dir = 'scenes'
)

# write_scene_list_html('result.html', scene_list)

for scene in scene_list:
    start, end = scene
    print(f'{start.get_seconds()}-{end.get_seconds()}') 

base_timecode is deprecated.


109 scenes detected!
0.0-57.682624999999994
57.682624999999994-58.808749999999996
58.808749999999996-61.561499999999995
61.561499999999995-65.27354166666666
65.27354166666666-69.90316666666666
69.90316666666666-71.98858333333332
71.98858333333332-76.15941666666666
76.15941666666666-78.41166666666666
78.41166666666666-107.232125
107.232125-112.48737499999999
112.48737499999999-114.69791666666666
114.69791666666666-131.46466666666666
131.46466666666666-136.38625
136.38625-164.164
164.164-173.88204166666665
173.88204166666665-179.304125
179.304125-180.38854166666664
180.38854166666664-188.98045833333333
188.98045833333333-207.70749999999998
207.70749999999998-216.34112499999998
216.34112499999998-222.22199999999998
222.22199999999998-225.099875
225.099875-226.85162499999998
226.85162499999998-229.39583333333331
229.39583333333331-231.98174999999998
231.98174999999998-240.61537499999997
240.61537499999997-242.15858333333333
242.15858333333333-246.99675
246.99675-258.4248333333333
258.42483

In [192]:
import pandas as pd
pd.read_csv('result.csv')

Frame Number      Timecode  content_val  delta_hue  delta_lum  \
0                 2  00:00:00.042     0.000000   0.000000   0.000000   
1                 3  00:00:00.083     0.000000   0.000000   0.000000   
2                 4  00:00:00.125     0.000000   0.000000   0.000000   
3                 5  00:00:00.167     0.000000   0.000000   0.000000   
4                 6  00:00:00.209     0.000000   0.000000   0.000000   
...             ...           ...          ...        ...        ...   
13742         13744  00:09:33.198     0.140272   0.000543   0.410292   
13743         13745  00:09:33.239     0.158131   0.000000   0.463189   
13744         13746  00:09:33.281     0.145842   0.013021   0.382785   
13745         13747  00:09:33.323     0.124584   0.000000   0.364936   
13746         13748  00:09:33.364     0.143790   0.001085   0.392985   

       delta_sat  
0       0.000000  
1       0.000000  
2       0.000000  
3       0.000000  
4       0.000000  
...          ...  
13742   0.009983  
13743   0.011203  
13744   0.041721  
13745   0.008816  
13746   0.037299  

[13747 rows x 6 columns]

In [193]:
scene_list[0]

(00:00:00.000 [frame=0, fps=23.976], 00:00:57.683 [frame=1383, fps=23.976])

In [195]:
change_points = []
for scene in scene_list:
    start, end = scene
    change_points.append([start.frame_num, end.frame_num])
change_points

[[0, 1383],
 [1383, 1410],
 [1410, 1476],
 [1476, 1565],
 [1565, 1676],
 [1676, 1726],
 [1726, 1826],
 [1826, 1880],
 [1880, 2571],
 [2571, 2697],
 [2697, 2750],
 [2750, 3152],
 [3152, 3270],
 [3270, 3936],
 [3936, 4169],
 [4169, 4299],
 [4299, 4325],
 [4325, 4531],
 [4531, 4980],
 [4980, 5187],
 [5187, 5328],
 [5328, 5397],
 [5397, 5439],
 [5439, 5500],
 [5500, 5562],
 [5562, 5769],
 [5769, 5806],
 [5806, 5922],
 [5922, 6196],
 [6196, 6499],
 [6499, 7078],
 [7078, 7291],
 [7291, 7325],
 [7325, 7343],
 [7343, 7364],
 [7364, 7397],
 [7397, 7412],
 [7412, 7427],
 [7427, 7442],
 [7442, 7458],
 [7458, 7473],
 [7473, 7629],
 [7629, 7904],
 [7904, 7939],
 [7939, 7996],
 [7996, 8094],
 [8094, 8144],
 [8144, 8172],
 [8172, 8234],
 [8234, 8313],
 [8313, 8425],
 [8425, 8560],
 [8560, 8665],
 [8665, 8811],
 [8811, 8998],
 [8998, 9129],
 [9129, 9225],
 [9225, 9244],
 [9244, 9269],
 [9269, 9361],
 [9361, 9393],
 [9393, 9459],
 [9459, 9545],
 [9545, 9602],
 [9602, 9654],
 [9654, 9689],
 [9689, 9709]

In [188]:
# data['change_points'] = change_points

[[0, 33],
 [33, 64],
 [64, 102],
 [102, 593],
 [593, 686],
 [686, 1230],
 [1230, 1693],
 [1693, 1728],
 [1728, 1759],
 [1759, 2215],
 [2215, 2691],
 [2691, 3600],
 [3600, 4214],
 [4214, 4603],
 [4603, 4647],
 [4647, 4774],
 [4774, 4948],
 [4948, 5363],
 [5363, 5827],
 [5827, 5920],
 [5920, 5942],
 [5942, 6279],
 [6279, 7396],
 [7396, 7969],
 [7969, 8611],
 [8611, 8973],
 [8973, 9063],
 [9063, 9332],
 [9332, 10597]]